"""
 File:   luima_law_segmenter.py
 Author: Batuhan Erden
"""

from luima_sbd.sbd_utils import text2sentences

from src.segmentation.segmenter import Segmenter


class LuimaLawSegmenter(Segmenter):

    def __init__(self, corpus):
        super().__init__(corpus=corpus)

    def generate_sentences(self, document_id):
        """
        Generates sentences from a document using a law-specific sentence segmenter (Luima)

        :param document_id: Document ID
        :return: Sentences generated from a document by Luima
        """

        plain_text = self.corpus.annotated_documents_by_id[document_id]["plainText"]
        indices = text2sentences(plain_text, offsets=True)

        return [
            {
                "text": plain_text[start_char:end_char],
                "start_char": start_char,
                "end_char": end_char,
            }
            for (start_char, end_char) in indices
        ]

    def apply_segmentation(self):
        """
        Generates sentences using a law-specific sentence segmenter (Luima)

        :return: Sentences generated by Luima
        """

        # Generate Luima sentences
        generated_sentences_by_document = {
            document_id: self.generate_sentences(document_id)
            for document_id in self.corpus.get_documents_split(self.corpus.train_spans)
        }

        # Analyze segmentation
        self.analyze_segmentation(name="Luima Segmentation",
                                  generated_sentences_by_document=generated_sentences_by_document)

        return generated_sentences_by_document

